package com.example.patrice_musicapp.models;

public enum Instruments {
    ACCORDIAN,
    ACOUSTIC_GUITAR,
    BAG_PIPES,
    BANJO,
    BASS_GUITAR,
    BASSOON,
    BELL,
    CELLO,
    CLARINET,
    DOUBLE_BASS,
    DRUMS,
    ELECTRIC_GUITAR,
    FLUTE,
    FRENCH_HORN,
    HARMONICA,
    KEYBOARD,
    OBOE,
    ORGAN,
    PERCUSSION,
    PIANO,
    SAXOPHONE,
    SOUND_ENGINEER,
    STEEL_PAN,
    TROMBONE,
    TRUMPET,
    TUBA,
    VIOLA,
    VIOLIN,
    VOCALS,
    XYLOPHONE
}
